function [fitresult, gof] = createFits(x1, y1, x2, y2)
%CREATEFITS(X1,Y1,X2,Y2)
%  Create fits.
%
%  Data for 'Ent. group' fit:
%      X Input : x1
%      Y Output: y1
%  Data for 'non-Ent. group' fit:
%      X Input : x2
%      Y Output: y2
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jan-2021 13:58:43

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Ent. group'.
[xData, yData] = prepareCurveData( x1, y1 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft );

% Plot fit with data.
figure;
% subplot(1,2,1)
plot( fitresult{1}, xData, yData);
% legend( h, 'y1 vs. x1', 'Ent. group', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes

hold on
%% Fit: 'non-Ent. group'.
[xData, yData] = prepareCurveData( x2, y2 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
% subplot(1,2,2)
h = plot( fitresult{2}, xData, yData );
% legend( h, 'y2 vs. x2', 'non-Ent. group', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes

xlabel( 'Gamma entrainment score', 'Interpreter', 'none' );
ylabel( 'Theta power', 'Interpreter', 'none' );
grid on
legend( 'Location', 'northwest', 'FontSize', 5)
